baseURL = 'https://mindgrep.github.io/'
languageCode = 'en-us'
title = "Sukis blog"

defaultContentLanguage = "en"

[taxonomies]
  subject = "subjects"
  teacher = "teachers"

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false
  [[module.imports]]
    path = "github.com/devcows/hugo-universal-theme"
    disable = true
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
    disable = true

[params]
title = "I'm Suki"
author = "Sukrish"
description = """
This is my blog!
I like to write about the things I find fun and enjoy!
"""
profilePicture = "images/big-chungus.png"


# For hugo-universal theme
logo = "images/big-chungus.png"
date_format = "2 January, 2006"
style = "marsala"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Teachers"
  weight = 200
  identifier = "teachers"
  url = "/teachers/"

  [[menu.main]]
  name = "Subjects"
  weight = 200
  identifier = "subjects"
  url = "/subjects/"
