baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = "Suki's blog"

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
title = "I'm Suki"
author = "Sukrish"
description = """
This is my blog!
I like to write about the things I find fun and enjoy!
"""
profilePicture = "images/big-chungus.png"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Pages"
  weight = 200
  identifier = "pages"
  url = "/page/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
